// Auto-generated by scripts/process-media.mjs
export const galleryItems = [
  {
    "src": "/media/gallery/105fcf6a-3670-43a0-b850-aa36cbb60972.jpg",
    "type": "image",
    "width": 1400,
    "height": 1400
  },
  {
    "src": "/media/gallery/headshot.jpg",
    "type": "image",
    "width": 788,
    "height": 1400
  },
  {
    "src": "/media/gallery/textgram-1538410217.jpg",
    "type": "image",
    "width": 1080,
    "height": 1080
  },
  {
    "src": "/media/gallery/dsc04487.jpg",
    "type": "image",
    "width": 1400,
    "height": 788
  },
  {
    "src": "/media/gallery/dsc04508.jpg",
    "type": "image",
    "width": 1400,
    "height": 788
  },
  {
    "src": "/media/gallery/ig-sotry-full.jpg",
    "type": "image",
    "width": 788,
    "height": 1400
  },
  {
    "src": "/media/gallery/img-20190405-154336-951.jpg",
    "type": "image",
    "width": 1080,
    "height": 1080
  },
  {
    "src": "/media/gallery/img-6545.jpg",
    "type": "image",
    "width": 787,
    "height": 1400
  },
  {
    "src": "/media/gallery/img-20190217-180508-691.jpg",
    "type": "image",
    "width": 1080,
    "height": 608
  },
  {
    "src": "/media/gallery/a7dc058c-472d-4682-9e9c-bbc96626b10a-2.jpg",
    "type": "image",
    "width": 788,
    "height": 1400
  },
  {
    "src": "/media/video/joined-video-a8888a9a4899420e9070a39efdb6d976.mp4",
    "poster": "/media/video/joined-video-a8888a9a4899420e9070a39efdb6d976.jpg",
    "type": "video",
    "width": 720,
    "height": 720
  },
  {
    "src": "/media/gallery/mockup-06.jpg",
    "type": "image",
    "width": 1400,
    "height": 1280
  },
  {
    "src": "/media/gallery/received-2243959395834170.jpg",
    "type": "image",
    "width": 1400,
    "height": 788
  },
  {
    "src": "/media/gallery/ig-5.jpg",
    "type": "image",
    "width": 1400,
    "height": 1400
  },
  {
    "src": "/media/gallery/60935867493-1305461b-0953-4689-9016-8d572b7599ba.jpg",
    "type": "image",
    "width": 1400,
    "height": 1050
  },
  {
    "src": "/media/gallery/darkroom-candle-mock-with-box.jpg",
    "type": "image",
    "width": 1400,
    "height": 935
  },
  {
    "src": "/media/gallery/img-20190627-135054-01.jpg",
    "type": "image",
    "width": 1400,
    "height": 1867
  },
  {
    "src": "/media/gallery/img-20190703-195737-003.jpg",
    "type": "image",
    "width": 1080,
    "height": 1080
  },
  {
    "src": "/media/gallery/8.jpg",
    "type": "image",
    "width": 1400,
    "height": 934
  },
  {
    "src": "/media/gallery/img-20190217-192052-906.jpg",
    "type": "image",
    "width": 1080,
    "height": 608
  },
  {
    "src": "/media/gallery/received-487680048378285.jpg",
    "type": "image",
    "width": 1400,
    "height": 1049
  },
  {
    "src": "/media/gallery/06.jpg",
    "type": "image",
    "width": 933,
    "height": 1400
  },
  {
    "src": "/media/gallery/img-5411.jpg",
    "type": "image",
    "width": 1400,
    "height": 1867
  },
  {
    "src": "/media/gallery/img-1996.jpg",
    "type": "image",
    "width": 1400,
    "height": 1867
  },
  {
    "src": "/media/video/cover.mp4",
    "poster": "/media/video/cover.jpg",
    "type": "video",
    "width": 1440,
    "height": 1080
  },
  {
    "src": "/media/gallery/femmeprid.jpg",
    "type": "image",
    "width": 800,
    "height": 800
  },
  {
    "src": "/media/gallery/sauna-mockup-03.jpg",
    "type": "image",
    "width": 1400,
    "height": 974
  },
  {
    "src": "/media/gallery/img-5412.jpg",
    "type": "image",
    "width": 1400,
    "height": 1867
  },
  {
    "src": "/media/gallery/scan-1.jpg",
    "type": "image",
    "width": 1885,
    "height": 1400
  },
  {
    "src": "/media/video/received-2496587707035397.mp4",
    "poster": "/media/video/received-2496587707035397.jpg",
    "type": "video",
    "width": 672,
    "height": 1312
  },
  {
    "src": "/media/gallery/60937874239-e9d613d2-9313-4750-a8f8-d643071c45a7.jpg",
    "type": "image",
    "width": 1400,
    "height": 1050
  },
  {
    "src": "/media/gallery/2019-02-17-01-41-48-3.jpg",
    "type": "image",
    "width": 788,
    "height": 1400
  },
  {
    "src": "/media/gallery/story1.jpg",
    "type": "image",
    "width": 906,
    "height": 1400
  },
  {
    "src": "/media/video/trim-ea80f08a-e9ac-4536-becf-8c3c1ac0b45c.mp4",
    "poster": "/media/video/trim-ea80f08a-e9ac-4536-becf-8c3c1ac0b45c.jpg",
    "type": "video",
    "width": 720,
    "height": 1280
  },
  {
    "src": "/media/gallery/img-20190217-192052-909.jpg",
    "type": "image",
    "width": 1080,
    "height": 608
  },
  {
    "src": "/media/video/builder.mp4",
    "poster": "/media/video/builder.jpg",
    "type": "video",
    "width": 1080,
    "height": 1920
  },
  {
    "src": "/media/gallery/received-527959360984961.jpg",
    "type": "image",
    "width": 1050,
    "height": 1400
  },
  {
    "src": "/media/gallery/ig-4.jpg",
    "type": "image",
    "width": 1400,
    "height": 1400
  },
  {
    "src": "/media/gallery/99d5201f-0ad7-49d3-9bed-e621921a89ff.jpg",
    "type": "image",
    "width": 1400,
    "height": 1400
  },
  {
    "src": "/media/gallery/mockup-07.jpg",
    "type": "image",
    "width": 935,
    "height": 1400
  },
  {
    "src": "/media/gallery/nya.jpg",
    "type": "image",
    "width": 1400,
    "height": 1400
  },
  {
    "src": "/media/gallery/img-4417.jpg",
    "type": "image",
    "width": 1400,
    "height": 1050
  },
  {
    "src": "/media/gallery/img-20190217-192052-908.jpg",
    "type": "image",
    "width": 1080,
    "height": 608
  },
  {
    "src": "/media/gallery/scan.jpg",
    "type": "image",
    "width": 1099,
    "height": 1400
  },
  {
    "src": "/media/gallery/img-3541.jpg",
    "type": "image",
    "width": 1400,
    "height": 1050
  },
  {
    "src": "/media/gallery/img-5891.jpg",
    "type": "image",
    "width": 1125,
    "height": 1305
  },
  {
    "src": "/media/gallery/img-5414.jpg",
    "type": "image",
    "width": 1400,
    "height": 1867
  },
  {
    "src": "/media/gallery/img-20180913-213142-405.jpg",
    "type": "image",
    "width": 728,
    "height": 1400
  },
  {
    "src": "/media/gallery/tea-larry.jpg",
    "type": "image",
    "width": 906,
    "height": 1400
  },
  {
    "src": "/media/video/instagram-reel-vertical-9-16-1080x1920-2.mp4",
    "poster": "/media/video/instagram-reel-vertical-9-16-1080x1920-2.jpg",
    "type": "video",
    "width": 1080,
    "height": 1920
  },
  {
    "src": "/media/video/vid2.mp4",
    "poster": "/media/video/vid2.jpg",
    "type": "video",
    "width": 1080,
    "height": 1920
  },
  {
    "src": "/media/gallery/6751dafe-3fb6-426d-b5a8-898030c898d5.jpg",
    "type": "image",
    "width": 1400,
    "height": 788
  },
  {
    "src": "/media/gallery/01-1.jpg",
    "type": "image",
    "width": 1400,
    "height": 847
  },
  {
    "src": "/media/gallery/img-8254.jpg",
    "type": "image",
    "width": 787,
    "height": 1400
  },
  {
    "src": "/media/gallery/fullsizer1.jpg",
    "type": "image",
    "width": 1050,
    "height": 1400
  },
  {
    "src": "/media/gallery/img-20191003-wa0003.jpg",
    "type": "image",
    "width": 1050,
    "height": 1400
  },
  {
    "src": "/media/gallery/img-5775.jpg",
    "type": "image",
    "width": 647,
    "height": 1400
  },
  {
    "src": "/media/gallery/sauna-mockup-01.jpg",
    "type": "image",
    "width": 1400,
    "height": 1233
  },
  {
    "src": "/media/gallery/img-6547.jpg",
    "type": "image",
    "width": 1400,
    "height": 1867
  },
  {
    "src": "/media/gallery/cam.jpg",
    "type": "image",
    "width": 1400,
    "height": 1400
  },
  {
    "src": "/media/gallery/tea-poster.jpg",
    "type": "image",
    "width": 1400,
    "height": 1400
  },
  {
    "src": "/media/gallery/img-7400.jpg",
    "type": "image",
    "width": 788,
    "height": 1400
  },
  {
    "src": "/media/gallery/img-3414.jpg",
    "type": "image",
    "width": 1400,
    "height": 1050
  },
  {
    "src": "/media/gallery/screenshot-20180714-111623-dropbox.jpg",
    "type": "image",
    "width": 908,
    "height": 1400
  },
  {
    "src": "/media/gallery/screen-shot-2021-09-07-at-10-13-50-am.jpg",
    "type": "image",
    "width": 893,
    "height": 895
  },
  {
    "src": "/media/gallery/pride-poster.jpg",
    "type": "image",
    "width": 906,
    "height": 1400
  },
  {
    "src": "/media/gallery/img-4024.jpg",
    "type": "image",
    "width": 1400,
    "height": 1050
  },
  {
    "src": "/media/video/mxm-pride.mp4",
    "poster": "/media/video/mxm-pride.jpg",
    "type": "video",
    "width": 1920,
    "height": 1080
  },
  {
    "src": "/media/gallery/mockup-02.jpg",
    "type": "image",
    "width": 1310,
    "height": 1400
  },
  {
    "src": "/media/gallery/screen-shot-2021-09-07-at-10-14-36-am.jpg",
    "type": "image",
    "width": 830,
    "height": 827
  },
  {
    "src": "/media/gallery/20190914-135453.jpg",
    "type": "image",
    "width": 1400,
    "height": 1050
  },
  {
    "src": "/media/gallery/img-20190217-192052-907.jpg",
    "type": "image",
    "width": 1080,
    "height": 607
  },
  {
    "src": "/media/gallery/sauna1.jpg",
    "type": "image",
    "width": 906,
    "height": 1400
  },
  {
    "src": "/media/video/comp-1.mp4",
    "poster": "/media/video/comp-1.jpg",
    "type": "video",
    "width": 1080,
    "height": 1920
  },
  {
    "src": "/media/gallery/60953335630-e4b77e01-250c-4fbd-8547-623f27bebbe5.jpg",
    "type": "image",
    "width": 1400,
    "height": 1050
  },
  {
    "src": "/media/gallery/img-20180913-173911-384.jpg",
    "type": "image",
    "width": 1400,
    "height": 1400
  },
  {
    "src": "/media/video/teaser.mp4",
    "poster": "/media/video/teaser.jpg",
    "type": "video",
    "width": 1080,
    "height": 1920
  },
  {
    "src": "/media/gallery/img-5415.jpg",
    "type": "image",
    "width": 1400,
    "height": 1867
  },
  {
    "src": "/media/gallery/img-6544.jpg",
    "type": "image",
    "width": 1400,
    "height": 788
  },
  {
    "src": "/media/gallery/zine-pic-1.jpg",
    "type": "image",
    "width": 1400,
    "height": 1153
  },
  {
    "src": "/media/gallery/dsc04517.jpg",
    "type": "image",
    "width": 788,
    "height": 1400
  },
  {
    "src": "/media/video/shortteaser-weekof.mp4",
    "poster": "/media/video/shortteaser-weekof.jpg",
    "type": "video",
    "width": 1080,
    "height": 1920
  },
  {
    "src": "/media/gallery/sauna-relax-flyer-crop.jpg",
    "type": "image",
    "width": 808,
    "height": 1223
  },
  {
    "src": "/media/gallery/slide-1.jpg",
    "type": "image",
    "width": 906,
    "height": 1400
  },
  {
    "src": "/media/gallery/60937876401-5e98053c-31fe-4d71-b3fa-27c42f405499.jpg",
    "type": "image",
    "width": 1400,
    "height": 1050
  },
  {
    "src": "/media/gallery/img-6548.jpg",
    "type": "image",
    "width": 787,
    "height": 1400
  },
  {
    "src": "/media/video/dancer.mp4",
    "poster": "/media/video/dancer.jpg",
    "type": "video",
    "width": 1080,
    "height": 1920
  },
  {
    "src": "/media/video/img-6543.mp4",
    "poster": "/media/video/img-6543.jpg",
    "type": "video",
    "width": 2160,
    "height": 3840
  }
];
